# Generated by Django 5.0 on 2023-12-22 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coderapp', '0002_curso_entregable_estudiante'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Estudiante',
            new_name='Cliente',
        ),
        migrations.RenameModel(
            old_name='Curso',
            new_name='Producto',
        ),
        migrations.RenameModel(
            old_name='Profesor',
            new_name='Vendedor',
        ),
        migrations.RenameModel(
            old_name='Entregable',
            new_name='Venta',
        ),
        migrations.AlterModelOptions(
            name='vendedor',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'Vendedores'},
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='camada',
            new_name='cantidad',
        ),
        migrations.RenameField(
            model_name='venta',
            old_name='fechaDeEntrega',
            new_name='fechaDeVenta',
        ),
    ]
